#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: Borough
main: net.peacefulcraft.borough.Borough
version: 0.0.1
api-version: 1.18
website: https://www.peacefulcraft.net/
depend: []
softdepend: [ "Vault" ]

commands:
  claim:
    description: Create, expand, and modify land claims.
    usage: /<command> [ add-admin | add-builder | add-moderator | create | delete | extend | info ] to use the example command.
  unclaim:
    description: Unclaim the chunk in which you stand.
    usage: /<command>
  boroughadmin:
    description: Admin commnad

permissions:
  pcn.staff:
    description: Give user staff permissions
